version: 1
sources:
  prd: docs/prd.md
  architecture: docs/architecture.md
  deployment: docs/deployment.md
  dbml: db/schema.dbml
  openapi: docs/openapi.yaml

tasks:
  - id: TK-001
    title: Пользователи и аутентификация (JWT 24h)
    order: 10
    status: done
    frRefs: [FR6]
    context:
      prd: "docs/prd.md#6.-Регистрация-и-вход"
      architecture: "docs/architecture.md#3.1-Регистрация-и-вход"
      dbml: "db/schema.dbml#users"
      openapi: "docs/openapi.yaml#/paths/~1auth~1register"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "В OpenAPI описаны /auth/register, /auth/login, /users/me; security bearer JWT 24h"
        done: true
      - text: "В DBML есть таблица users со строго перечисленными полями"
        done: true
      - text: "Бэкенд реализует регистрацию, логин и /users/me; соответствует OpenAPI"
        done: true
      - text: "Health /api/health возвращает 200 при локальном запуске docker-compose"
        done: true
    subtasks:
      - id: TK-001/AN
        role: AN
        title: Детальная спецификация по аутентификации
        status: done
        outputs:
          - docs/specs/TK-001.md
      - id: TK-001/BE
        role: BE
        title: Реализация backend аутентификации
        status: done
      - id: TK-001/FE
        role: FE
        title: Форма логина и состояние профиля
        status: done
      - id: TK-001/DV
        role: DV
        title: Переменные окружения JWT и прокси в Caddy
        status: done

  - id: TK-002
    title: Инициативы — создание и просмотр карточки
    order: 20
    status: done
    frRefs: [FR1]
    context:
      prd: "docs/prd.md#FR1.-Создание-инициативы"
      architecture: "docs/architecture.md#3.2-Создание-инициативы"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}"
      deployment: "docs/deployment.md#health-проверки"
    acceptanceCriteria:
      - text: "POST /initiatives создаёт инициативу, валидации названия/описания соблюдены"
        done: true
      - text: "GET /initiatives/{id} возвращает инициативу с автором и датами"
        done: true
      - text: "Markdown описания корректно передаётся и хранится"
        done: true
      - text: "Миграции для таблицы initiatives применяются автоматически"
        done: true
    subtasks:
      - id: TK-002/AN
        role: AN
        title: Спецификация по созданию/деталям инициативы
        status: done
        outputs:
          - docs/specs/TK-002.md
      - id: TK-002/BE
        role: BE
        title: Эндпоинты POST /initiatives, GET /initiatives/{id}
        status: done
      - id: TK-002/FE
        role: FE
        title: Экран создания инициативы и карточка
        status: done
      - id: TK-002/DV
        role: DV
        title: Миграции БД для initiatives
        status: done

  - id: TK-003
    title: Атрибуты оценки и расчёт веса инициативы
    order: 30
    status: done
    frRefs: [FR3]
    context:
      prd: "docs/prd.md#FR3.-Атрибуты-оценки-инициативы-1–5"
      architecture: "docs/architecture.md#3.3-Оценка-инициативы"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/components/schemas/InitiativeUpdate"
      deployment: "docs/deployment.md#мониторинг-и-метрики"
    acceptanceCriteria:
      - text: "PATCH /initiatives/{id} принимает value/speed/cost 1–5 и обновляет weight"
        done: true
      - text: "Формула веса соответствует PRD (0.5*value + 0.3*speed − 0.2*cost)"
        done: true
      - text: "В БД CHECK‑ограничения на диапазон 1–5 или NULL"
        done: true
      - text: "Фронтенд обновляет вес на карточке после сохранения"
        done: true
    subtasks:
      - id: TK-003/AN
        role: AN
        title: Спецификация по атрибутам и весу
        status: done
        outputs:
          - docs/specs/TK-003.md
      - id: TK-003/BE
        role: BE
        title: Реализация обновления атрибутов и пересчёта веса
        status: done
      - id: TK-003/FE
        role: FE
        title: Контролы 1–5 и показ веса на карточке
        status: done
      - id: TK-003/DV
        role: DV
        title: Миграции CHECK ограничений
        status: done

  - id: TK-004
    title: Комментарии к инициативам (чат‑лента)
    order: 40
    status: done
    frRefs: [FR2]
    context:
      prd: "docs/prd.md#FR2.-Комментарии-в-формате-чата"
      architecture: "docs/architecture.md#3.5-Комментарий-к-инициативе"
      dbml: "db/schema.dbml#comments"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}~1comments"
      deployment: "docs/deployment.md#health-проверки"
    acceptanceCriteria:
      - text: "POST /initiatives/{id}/comments создаёт комментарий; валидации 1–1000 символов"
        done: true
      - text: "GET /initiatives/{id}/comments возвращает хронологический список"
        done: true
      - text: "Фронтенд блокирует отправку пустых сообщений"
        done: true
      - text: "Индикаторы загрузки/ошибок присутствуют"
        done: true
    subtasks:
      - id: TK-004/AN
        role: AN
        title: Спецификация ленты комментариев
        status: done
        outputs:
          - specs/TK-004.md
      - id: TK-004/BE
        role: BE
        title: Эндпоинты комментариев и связи в БД
        status: done
      - id: TK-004/FE
        role: FE
        title: UI чата с отправкой и списком
        status: done
      - id: TK-004/DV
        role: DV
        title: Миграции для comments и индексы
        status: done

  - id: TK-005
    title: Список инициатив — фильтры и сортировка по весу
    order: 50
    status: done
    frRefs: [FR5]
    context:
      prd: "docs/prd.md#FR5.-Список-инициатив-фильтры-и-сортировка"
      architecture: "docs/architecture.md#3.6-Список-инициатив-фильтр-и-сортировка"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/paths/~1initiatives"
      deployment: "docs/deployment.md#мониторинг-и-метрики"
    acceptanceCriteria:
      - text: "GET /initiatives поддерживает filter=all|mineCreated|assignedToMe и пагинацию"
        done: true
      - text: "Сортировка: weight desc, затем createdAt desc"
        done: true
      - text: "Фронтенд — табы фильтров, стабильная сортировка, скелетоны"
        done: true
      - text: "Индексы в БД под запросы списка"
        done: true
    subtasks:
      - id: TK-005/AN
        role: AN
        title: Спецификация списка и фильтров
        status: done
        outputs:
          - docs/specs/TK-005.md
      - id: TK-005/BE
        role: BE
        title: Эндпоинт GET /initiatives с фильтрами/сортировкой
        status: done
      - id: TK-005/FE
        role: FE
        title: Экран списка с фильтрами и пагинацией
        status: done
      - id: TK-005/DV
        role: DV
        title: Поддержка индексов и профилирование запросов
        status: done

  - id: TK-006
    title: Назначение ответственного
    order: 60
    status: done
    frRefs: [FR4]
    context:
      prd: "docs/prd.md#FR4.-Назначение-ответственного"
      architecture: "docs/architecture.md#3.4-Назначение-ответственного"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/components/schemas/InitiativeUpdate"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "PATCH /initiatives/{id} поддерживает assigneeId (uuid|null)"
        done: true
      - text: "Фронтенд — селект пользователя и возможность снять назначение"
        done: true
      - text: "OpenAPI/DBML синхронизированы по полю assignee"
        done: true
      - text: "Покрыты ошибки и UX‑состояния"
        done: true
    subtasks:
      - id: TK-006/AN
        role: AN
        title: Спецификация назначения ответственного
        status: done
        outputs:
          - specs/TK-006.md
      - id: TK-006/BE
        role: BE
        title: Обновление assignee и возврат карточки
        status: done
      - id: TK-006/FE
        role: FE
        title: UI выбора ответственного
        status: done
      - id: TK-006/DV
        role: DV
        title: Индексы и нагрузочное тестирование запроса списка
        status: done

  - id: TK-007
    title: V2 — Верификация e‑mail и доменное ограничение регистрации
    order: 70
    status: planned
    frRefs: [V2-EmailVerification, V2-RegistrationDomain]
    context:
      prd: "docs/prd.md#9.4-Регистрация-только-axenix.pro--подтверждение-e‑mail-кодом"
      architecture: "docs/architecture.md#аутентификация-и-e-mail-верификация" 
      dbml: "db/schema.dbml#email_codes"
      openapi: "docs/openapi.yaml#/paths/~1auth~1request-email-code"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "В OpenAPI описаны POST /auth/request-email-code и расширенный /auth/register (email, emailCode)"
        done: true
      - text: "В DBML/миграциях есть таблица email_codes с TTL полями и индексами"
        done: true
      - text: "На сервере жёсткая проверка домена e‑mail (AXENIX_EMAIL_DOMAIN) и rate‑limit на запрос кода"
        done: false
      - text: "Регистрация возможна только с валидным кодом; неверный/просроченный код отклоняется"
        done: false
      - text: "Отправка кода через Mailgun; секреты берутся из .env (MAILGUN_API_KEY/DOMAIN/FROM)"
        done: false
      - text: "Фронтенд: в форме регистрации поля e‑mail, кнопка 'Получить код', поле кода и обработка ошибок"
        done: false
    subtasks:
      - id: TK-007/AN
        role: AN
        title: Спецификация потока регистрации с подтверждением e‑mail
        status: done
        outputs:
          - docs/specs/TK-007.md
      - id: TK-007/BE
        role: BE
        title: Эндпоинт /auth/request-email-code и серверная валидация email+code
        status: planned
      - id: TK-007/FE
        role: FE
        title: Обновление формы регистрации (email, запрос и ввод кода)
        status: planned
      - id: TK-007/DV
        role: DV
        title: Переменные окружения Mailgun и домена, док обновления деплоя
        status: planned

  - id: TK-008
    title: V2 — Роли и права админов; логическое удаление инициатив
    order: 80
    status: spec-prepared
    frRefs: [V2-Roles, V2-AdminDelete, V2-AdminUpdateFields]
    context:
      prd: "docs/prd.md#9.1-Роли-и-разграничение-прав"
      architecture: "docs/architecture.md#авторизация-и-права"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}~1delete"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "Профиль пользователя (GET /users/me) содержит isAdmin, определяемый по ADMIN_EMAILS"
        done: false
      - text: "PATCH /initiatives/{id}: поля assignee/value/speed/cost доступны только админу; non-admin получает 403"
        done: false
      - text: "DELETE /initiatives/{id}: логическое удаление (is_deleted=true) доступно только админу"
        done: false
      - text: "Удалённые инициативы отсутствуют в списках и по id отдают 404"
        done: false
      - text: "Фронтенд: не‑админ видит поля в режиме чтения; админ видит кнопку 'Удалить'"
        done: false
      - text: "ADMIN_EMAILS и связанные настройки берутся из .env; логи без утечки секретов"
        done: false
    subtasks:
      - id: TK-008/AN
        role: AN
        title: Спецификация ролей и матрицы прав
        status: done
        outputs:
          - docs/specs/TK-008.md
      - id: TK-008/BE
        role: BE
        title: Авторизация по ролям, ограничение PATCH, реализация DELETE
        status: planned
      - id: TK-008/FE
        role: FE
        title: Read-only для не‑админов, UI удаления для админов
        status: planned
      - id: TK-008/DV
        role: DV
        title: Переменные окружения ADMIN_EMAILS и инструкции по развертыванию
        status: planned

  - id: TK-009
    title: V2 — Голосование (up/down) и сортировка по голосам
    order: 90
    status: spec-prepared
    frRefs: [V2-Voting, V2-SortByVotes]
    context:
      prd: "docs/prd.md#9.2-Голосование-за-инициативы"
      architecture: "docs/architecture.md#агрегации-и-запросы"
      dbml: "db/schema.dbml#initiative_votes"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}~1vote"
      deployment: "docs/deployment.md#мониторинг-и-метрики"
    acceptanceCriteria:
      - text: "В OpenAPI описаны поля upVotes/downVotes/voteScore/currentUserVote и POST /initiatives/{id}/vote"
        done: true
      - text: "В DBML/миграциях есть initiative_votes с уникальным (initiative_id, user_id) и CHECK value IN (-1,1)"
        done: true
      - text: "POST /initiatives/{id}/vote: создание/изменение/снятие голоса, возврат обновлённой инициативы"
        done: false
      - text: "GET /initiatives поддерживает sort=votes; вторичная сортировка по дате"
        done: false
      - text: "Агрегаты голосов корректны и производительны; фильтруются удалённые инициативы"
        done: false
      - text: "Фронтенд: кнопки up/down, индикация текущего голоса, подсчёты и переключатель сортировки"
        done: false
    subtasks:
      - id: TK-009/AN
        role: AN
        title: Спецификация голосования и агрегаций
        status: done
        outputs:
          - docs/specs/TK-009.md
      - id: TK-009/BE
        role: BE
        title: Эндпоинт голосования и агрегированные выборки списка
        status: planned
      - id: TK-009/FE
        role: FE
        title: UI голосования и сортировки по голосам
        status: planned
      - id: TK-009/DV
        role: DV
        title: Профилирование запросов и индексы под сортировку по голосам
        status: planned
