version: 1
sources:
  prd: docs/prd.md
  architecture: docs/architecture.md
  deployment: docs/deployment.md
  dbml: db/schema.dbml
  openapi: docs/openapi.yaml

tasks:
  - id: TK-001
    title: Пользователи и аутентификация (JWT 24h)
    order: 10
    status: done
    frRefs: [FR6]
    context:
      prd: "docs/prd.md#6.-Регистрация-и-вход"
      architecture: "docs/architecture.md#3.1-Регистрация-и-вход"
      dbml: "db/schema.dbml#users"
      openapi: "docs/openapi.yaml#/paths/~1auth~1register"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "В OpenAPI описаны /auth/register, /auth/login, /users/me; security bearer JWT 24h"
        done: true
      - text: "В DBML есть таблица users со строго перечисленными полями"
        done: true
      - text: "Бэкенд реализует регистрацию, логин и /users/me; соответствует OpenAPI"
        done: true
      - text: "Health /api/health возвращает 200 при локальном запуске docker-compose"
        done: true
    subtasks:
      - id: TK-001/AN
        role: AN
        title: Детальная спецификация по аутентификации
        status: done
        outputs:
          - docs/specs/TK-001.md
      - id: TK-001/BE
        role: BE
        title: Реализация backend аутентификации
        status: done
      - id: TK-001/FE
        role: FE
        title: Форма логина и состояние профиля
        status: done
      - id: TK-001/DV
        role: DV
        title: Переменные окружения JWT и прокси в Caddy
        status: done

  - id: TK-002
    title: Инициативы — создание и просмотр карточки
    order: 20
    status: done
    frRefs: [FR1]
    context:
      prd: "docs/prd.md#FR1.-Создание-инициативы"
      architecture: "docs/architecture.md#3.2-Создание-инициативы"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}"
      deployment: "docs/deployment.md#health-проверки"
    acceptanceCriteria:
      - text: "POST /initiatives создаёт инициативу, валидации названия/описания соблюдены"
        done: true
      - text: "GET /initiatives/{id} возвращает инициативу с автором и датами"
        done: true
      - text: "Markdown описания корректно передаётся и хранится"
        done: true
      - text: "Миграции для таблицы initiatives применяются автоматически"
        done: true
    subtasks:
      - id: TK-002/AN
        role: AN
        title: Спецификация по созданию/деталям инициативы
        status: done
        outputs:
          - docs/specs/TK-002.md
      - id: TK-002/BE
        role: BE
        title: Эндпоинты POST /initiatives, GET /initiatives/{id}
        status: done
      - id: TK-002/FE
        role: FE
        title: Экран создания инициативы и карточка
        status: done
      - id: TK-002/DV
        role: DV
        title: Миграции БД для initiatives
        status: done

  - id: TK-003
    title: Атрибуты оценки и расчёт веса инициативы
    order: 30
    status: done
    frRefs: [FR3]
    context:
      prd: "docs/prd.md#FR3.-Атрибуты-оценки-инициативы-1–5"
      architecture: "docs/architecture.md#3.3-Оценка-инициативы"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/components/schemas/InitiativeUpdate"
      deployment: "docs/deployment.md#мониторинг-и-метрики"
    acceptanceCriteria:
      - text: "PATCH /initiatives/{id} принимает value/speed/cost 1–5 и обновляет weight"
        done: true
      - text: "Формула веса соответствует PRD (0.5*value + 0.3*speed − 0.2*cost)"
        done: true
      - text: "В БД CHECK‑ограничения на диапазон 1–5 или NULL"
        done: true
      - text: "Фронтенд обновляет вес на карточке после сохранения"
        done: true
    subtasks:
      - id: TK-003/AN
        role: AN
        title: Спецификация по атрибутам и весу
        status: done
        outputs:
          - docs/specs/TK-003.md
      - id: TK-003/BE
        role: BE
        title: Реализация обновления атрибутов и пересчёта веса
        status: done
      - id: TK-003/FE
        role: FE
        title: Контролы 1–5 и показ веса на карточке
        status: done
      - id: TK-003/DV
        role: DV
        title: Миграции CHECK ограничений
        status: done

  - id: TK-004
    title: Комментарии к инициативам (чат‑лента)
    order: 40
    status: spec-prepared
    frRefs: [FR2]
    context:
      prd: "docs/prd.md#FR2.-Комментарии-в-формате-чата"
      architecture: "docs/architecture.md#3.5-Комментарий-к-инициативе"
      dbml: "db/schema.dbml#comments"
      openapi: "docs/openapi.yaml#/paths/~1initiatives~1{id}~1comments"
      deployment: "docs/deployment.md#health-проверки"
    acceptanceCriteria:
      - text: "POST /initiatives/{id}/comments создаёт комментарий; валидации 1–1000 символов"
        done: false
      - text: "GET /initiatives/{id}/comments возвращает хронологический список"
        done: false
      - text: "Фронтенд блокирует отправку пустых сообщений"
        done: false
      - text: "Индикаторы загрузки/ошибок присутствуют"
        done: false
    subtasks:
      - id: TK-004/AN
        role: AN
        title: Спецификация ленты комментариев
        status: done
        outputs:
          - specs/TK-004.md
      - id: TK-004/BE
        role: BE
        title: Эндпоинты комментариев и связи в БД
        status: planned
      - id: TK-004/FE
        role: FE
        title: UI чата с отправкой и списком
        status: planned
      - id: TK-004/DV
        role: DV
        title: Миграции для comments и индексы
        status: planned

  - id: TK-005
    title: Список инициатив — фильтры и сортировка по весу
    order: 50
    status: spec-prepared
    frRefs: [FR5]
    context:
      prd: "docs/prd.md#FR5.-Список-инициатив-фильтры-и-сортировка"
      architecture: "docs/architecture.md#3.6-Список-инициатив-фильтр-и-сортировка"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/paths/~1initiatives"
      deployment: "docs/deployment.md#мониторинг-и-метрики"
    acceptanceCriteria:
      - text: "GET /initiatives поддерживает filter=all|mineCreated|assignedToMe и пагинацию"
        done: false
      - text: "Сортировка: weight desc, затем createdAt desc"
        done: false
      - text: "Фронтенд — табы фильтров, стабильная сортировка, скелетоны"
        done: false
      - text: "Индексы в БД под запросы списка"
        done: false
    subtasks:
      - id: TK-005/AN
        role: AN
        title: Спецификация списка и фильтров
        status: done
        outputs:
          - docs/specs/TK-005.md
      - id: TK-005/BE
        role: BE
        title: Эндпоинт GET /initiatives с фильтрами/сортировкой
        status: planned
      - id: TK-005/FE
        role: FE
        title: Экран списка с фильтрами и пагинацией
        status: planned
      - id: TK-005/DV
        role: DV
        title: Поддержка индексов и профилирование запросов
        status: planned

  - id: TK-006
    title: Назначение ответственного
    order: 60
    status: spec-prepared
    frRefs: [FR4]
    context:
      prd: "docs/prd.md#FR4.-Назначение-ответственного"
      architecture: "docs/architecture.md#3.4-Назначение-ответственного"
      dbml: "db/schema.dbml#initiatives"
      openapi: "docs/openapi.yaml#/components/schemas/InitiativeUpdate"
      deployment: "docs/deployment.md#переменные-окружения"
    acceptanceCriteria:
      - text: "PATCH /initiatives/{id} поддерживает assigneeId (uuid|null)"
        done: false
      - text: "Фронтенд — селект пользователя и возможность снять назначение"
        done: false
      - text: "OpenAPI/DBML синхронизированы по полю assignee"
        done: false
      - text: "Покрыты ошибки и UX‑состояния"
        done: false
    subtasks:
      - id: TK-006/AN
        role: AN
        title: Спецификация назначения ответственного
        status: done
        outputs:
          - specs/TK-006.md
      - id: TK-006/BE
        role: BE
        title: Обновление assignee и возврат карточки
        status: planned
      - id: TK-006/FE
        role: FE
        title: UI выбора ответственного
        status: planned
      - id: TK-006/DV
        role: DV
        title: Индексы и нагрузочное тестирование запроса списка
        status: planned
